### PR TITLE
feat: brand consolodation

### PR DESCRIPTION
**Pull request by Alessandro100**
closes: #756 

**Summary:**

Mobility database is a product of MobilityData and as such this PR introduces more styling elements to better align with the MobilityData brand as seen on mobilitydata.org

This PR also consolidates random colors and assures that elements on the web app use colors directly from the theme

Biggest changes
- Buttons now use the MobilityData secondary font
- Header elements have similar hover animations to the mobilitydata.org website (including styling for mobile)

**Expected behavior:** 

The application should work the same, just different styling

**Testing tips:**

Go through the application and try to find visual defects

**What's next**
- Revisit way of implementing styling (instead of always having inline styling)
- Fix the favicon size (to match the mobilitydata.org) and possibly slightly different color
- Get a MobilityDatabase logo image done and implement it
- Remove old components (LegacyHome, Contribute)
- Make reusable styling components (Page Headers + content box)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [X] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [X] Linked all relevant issues
- [X] Include screenshot(s) showing how this pull request works and fixes the issue(s)

Current
image
Screenshot 2024-10-24 at 11 54 23

After
image
Screenshot 2024-10-24 at 11 54 34

Active Tab
image

### CODE REVIEW

**Review by cka-y — APPROVED** [review]
LGTM! 🤩

[nit] Noticed a little inconsistency: when hovering over linked elements in [https://gtfs-validator.mobilitydata.org/](https://gtfs-validator.mobilitydata.org/), the color changes, but it doesn’t in the Mobility Database. Maybe we could align the behavior for consistency? 

image

**Comment by Alessandro100** [comment]
Good point, I checked on the mobilitydata.org website and they have those types of links in the primary colour but they don't change color on hover

https://mobilitydata.org/what-we-do/
image

This gives me the idea that the validator could use some minor UI touch ups

**Comment by qcdyx** [comment]
Nitpick - Line above Text: I noticed there's a line above the "Explore and Access Global Transit Data" text. It slightly crowds the content. Removing it may make the header feel more spacious.

image
image

I also feel this isn’t something exclusive to the dev team. Perhaps after the summit, we could organize an internal vote to gather wider organizational feedback on these visual and branding changes.

**Comment by emmambd** [comment]
@Alessandro100 I think the line is good! I agree with @qcdyx that more padding between the homepage heading and the nav line would be good though.

I don't think we should design by committee - any more comprehensive visual re-design we do would be with a designer, but I don't anticipate one in the next 3-6 months. This looks great and provides more visual interest on the site! Thanks for this great work.

**Pull request merged**
