### PR TITLE
fix: 688 feed page minor UI fixes pre release

### LINKED ISSUE #688: Feed page: Minor UI fixes pre-release
### Describe the bug

1. Transit provider field in feed summary shouldn’t be bulleted when there’s only 1 provider (big space between it and the next field)
2. Authentication type shouldn't show if type is 0. Example: https://qa.mobilitydatabase.org/feeds/mdb-850
3. Feed contact email shouldn't show a colon at the end. Example: https://qa.mobilitydatabase.org/feeds/mdb-243
4. Update “Unable to generate validation report” notice to “Validation report not available” 

### Steps/Code to Reproduce

Go to an individual feed at https://qa.mobilitydatabase.org/

### Expected Results

1. Transit provider field in feed summary shouldn’t be bulleted when there’s only 1 provider
2. Authentication type shouldn't show if type is 0
3. Feed contact email shouldn't show a colon at the end.
4. In cases where a dataset doesn't have a validation report, should show "Validation report not available” in the dataset history row

### Actual Results

1. Transit provider field is bulleted when there's only 1 provider
2. If auth type is 0, Authentication Type still shows.
3. no colon at the end of Feed contact email
4. In "Run Validator Yourself", should show "Validation report not available” instead of “Unable to generate validation report” 

### Screenshots

1. Transit provider field is bulleted when there's only 1 provider
2. Authentication type
Image

3. should remove the colon
Image

4. should show "Validation report not available” instead of “Unable to generate validation report” 
image

### Files used

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by qcdyx**
**Summary:**

Closes #688 

**Expected behavior:** 
1. Transit provider field in feed summary shouldn’t be bulleted when there’s only 1 provider
image

2. Authentication type shouldn't show if type is 0
image

3. Feed contact email shouldn't show a colon at the end
image
 
4. In cases where a dataset doesn't have a validation report, should show "Validation report not available” in the dataset history row
image

**Testing tips:**

Provide tips, procedures and sample files on how to test the feature.
Testers are invited to follow the tips AND to try anything they deem relevant outside the bounds of the testing tips. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Review by jcpitre — APPROVED** [review]
LGTM!
(but what do I know about UI?)

**Comment by emmambd** [comment]
@qcdyx Can we remove the additional space at the end of the transit provider line?

**Comment by qcdyx** [comment]
@emmambd 
image

**Review by Alessandro100 — APPROVED** [review]
LGTM!

**Pull request merged**
