### PR TITLE
feat: Combine the two openapi files

### LINKED ISSUE #146: Remove OpenApi schema files duplication
# Description

As part of #144, the OpenApi schema is expressed in two files with only the authentication section as a differentiator. This was necessary as the API is behind a GCP Identity Aware Proxy that modifies the authentication headers.  However, it might be a source of conflict, and the two files might reflect different specs due to a copy/paste operation.

# Solution

Enhance the api-gen.sh script to consume a unified OpenApi file and remove the "duplicated" schema file from git.

### PR DESCRIPTION
**Pull request by Neo2308**
**Summary:**

Combine the two openapi files DatabaseCatalogAPI.yaml and DatabaseCatalogAPI_IAP.yaml
Fixes #146 & #203.

**Expected behavior:** 
These two files differ only by one line for the the type of authentication.
DatabaseCatalogAPI.yaml is for the public interface and DatabaseCatalogAPI_IAP.yaml is used internally after requests have been processed by the dispatcher.
Both files could be combined in a source file and recreated during the build process by substituting the authentication line.

**Testing tips:**

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Add or update any needed documentation to the repo
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by Neo2308** [comment]
Could someone help with the failing builds on this PR?
@jcpitre could you review this PR?

**Comment by jcpitre** [comment]
The Github action uses a secret that is not available in your fork.

**Comment by davidgamez** [comment]
Hi @Neo2308, as pointed out by @jcpitre , we had a dependency on GCP credentials for testing. This dependency was removed on #218. Your PR looks green now. Thanks!

**Review by davidgamez — APPROVED** [review]
LGTM

**Pull request merged**
