### PR TITLE
feat: show a snackbar when refresh access token API call failed

### LINKED ISSUE #136: Refresh access token action should reflect status of the ongoing action
### Describe the problem

The Refresh Access Token action doesn't prompt the user when the API call is in process nor any feedback if an error occurred. Find below a screenshot of cases when the token API call fails and there is no feedback; only a console error is shown.
Screenshot 2023-10-19 at 2 55 16 PM

### Proposed solution

When refreshing the token:
- Clear the currently visible token
- Add a message or a loading spinner 
- Show the refreshed token after the Token API call success
- Show an error when Token API fails

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qcdyx**
**Summary:**

Closes #136 

**Expected behavior:** 
1. turn off Wifi
2. Click Refresh Access Token button
3. A snack bar with error message shown on the top center of your browser

New Testing steps:
Login
Click generate access token
Turn off Wifi
Click refresh access token icon button
A snackbar showing error message should displayed

image

**Testing tips:**

Provide tips, procedures and sample files on how to test the feature.
Testers are invited to follow the tips AND to try anything they deem relevant outside the bounds of the testing tips. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by cka-y** [comment]
Can you add a screenshot of what the error looks like or provide testing steps to trigger the display?

**Comment by cka-y** [comment]
Just to make sure I understand, the snack bar is on the bottom of the page and displays "API Test", while we have an alert on top that displays the error? If my understanding is right :
- I think the alert needs the be closer to where the error originated from i.e. access token generation. I would suggest under the access token display box
- Why do we need a snakbar if it just displays "API Test"?

**Comment by cka-y** [comment]
In the case the token is generated for the first time and clicking on the `GENERATE ACCESS TOKEN` button results in an error, we should not see the input box or the time until expiration with an empty string like in the screenshot bellow. I think the display should just remain the generation initial button.
image

**Comment by qcdyx** [comment]
image
testing steps:
1. Login
2. Turn off Wifi
3. Click Generate Access Token button
4. A snackbar displays the error msg and Generate Access Token button is still there. @cka-y

**Review by cka-y — APPROVED** [review]

**Pull request merged**
