### PR TITLE
feat: add static content pages to website

### LINKED ISSUE #185: Add static content pages to website
Composites of Mobility Database website pages to replace the content on database.mobilitydata.org: 

- [Homepage](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=606-441&mode=dev)
- [About](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=753-6391&mode=dev)
- [FAQ](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=753-6391&mode=dev)
- [Contribute a Feed](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=660-1324&mode=dev)

### PR DESCRIPTION
**Pull request by cka-y**
**Summary:**
Closes #185 
Adding static pages to the mobility database website.

**Expected behavior:** 
- [Homepage](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=606-441&mode=dev)
- [About](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=753-6391&mode=dev)
- [FAQ](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=753-6391&mode=dev)
- [Contribute a Feed](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=660-1324&mode=dev)

**Testing tips:**
Visit the pages

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Review by emmambd — COMMENTED** [review]
@cka-y A few minor changes: 

1) Can we make "The Mobility Database" on the homepage left align with Mobility Database in the header? 

2) Title and description on homepage should stack rather than be in a 2 column layout on mobile sizes. 
Screenshot 2024-01-03 at 1 43 41 PM

3) (Upon further thought) Move the google form up on https://mobility-feeds-dev--pr-199-uyw0bjbf.web.app/contribute so it's before the Q&A section and more visible.

**Review by qcdyx — APPROVED** [review]
LGTM

**Comment by cka-y** [comment]
Waiting for @emmambd approval before merge

**Comment by emmambd** [comment]
@cka-y All above notes are fixed! The Mobility Database text is really large on mobile though - should be responsive to screen size and then we're good to merge. 
Screenshot 2024-01-04 at 1 28 47 PM

**Comment by cka-y** [comment]
@emmambd updated ✅
image

**Comment by emmambd** [comment]
@cka-y LGTM!

**Pull request closed without merging**
