### PR TITLE
feat: add search box to home page

### PR DESCRIPTION
**Pull request by indraneel**
**Summary:**

Should close what's left of #347 

image

**Expected behavior:** 

- makes a Search box available on home page
- navigates to `/feeds?q=<search query>` w/ search text contents 

**Testing tips:**
- type in search query and press "enter" key or click "search" button

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Add or update any needed documentation to the repo
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by Alessandro100** [comment]
[small] For the search button, can you add the style `height: '55px' ` so the button matches the height of the input and matches the search page styling?

**Review by Alessandro100 — APPROVED** [review]
left a small styling comment but otherwise works great!

**Comment by emmambd** [comment]
@indraneel Minor edit re: placeholder test (e.g. "New York" or "Carris Metropolitana")

**Comment by davidgamez** [comment]
A question for @emmambd, what is the expected behavior of a click in the search button with _empty search_? Currently, nothing happens. At the feeds page, a search is executed, returning the first page of _all feeds results_

**Comment by emmambd** [comment]
@davidgamez Good point - it should be the same behavior as the feeds page (empty = returns all feeds)

**Comment by emmambd** [comment]
Also, would be nice for the buttons not to have drop shadow (original design was flat)

**Comment by indraneel** [comment]
image

**Comment by indraneel** [comment]
@emmambd is this what you meant?
image

**Review by davidgamez — APPROVED** [review]
LGTM!

**Pull request merged**
