### PR TITLE
feat: metrics using single feature truth

### LINKED ISSUE #820: Update feature groups on UI to match Features.MD
### Describe the problem

Currently, there are features on the UI who don't belong to their corresponding feature group: 

Image

This needs to be updated to ensure that each feature belongs to the corresponding feature group in [features.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md)

### Proposed solution

- Update feature groups so each feature belongs to a group in [features.md](https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md). This should be tested by checking [the GTFS metrics -> feature page](https://mobilitydatabase.org/metrics/gtfs/features) 
- Update documentation links on the Features Metrics pages https://mobilitydatabase.org/metrics/gtfs/features (the info tooltips)

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alessandro100**
closes #820 
**Summary:**

Updates the feature support to 6.0 for the gtfs metrics. Also consolidates the Features data to a source of truth in the frontend. Added sub group feature to metrics to accommodate Fares V2 and Flex

**Expected behavior:** 

Metrics in the features should have no empty groups and should be displayed correctly

**Testing tips:**

Go to the GTFS metrics page (Feeds / Features) and play around with to make sure the features are displaying correctly

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [X] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [X] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

image
image
Subgroup depicted as Icon + tooltip
image

Screenshot with prod analytics
image

### CODE REVIEW

**Comment by emmambd** [comment]
@Alessandro100 Can we add Flex as a subgroup? It's all features in Flexible services except Continuous Stops 

Also to be clear, we'll use this for internal analytics, but not the public facing search (as discussed in #806 - there's alignment in using tags for extensions like Flex and Fares v2 outside of features)

**Comment by emmambd** [comment]
@Alessandro100 It looks like the changes to features from FEATURES.md are not reflected here: https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md#feature-migration

**Comment by emmambd** [comment]
@cka-y Any clue about why the counts have changed for the ones where only the name has changed (e.g Bike Allowed, or Text-to-Speech)

image

**Comment by cka-y** [comment]
@emmambd I'm not sure I fully understand the question, but here's some context that might help:

- When the name of a feature changes, it’s treated as a new feature from the metrics' perspective. It’s not considered a feature update. 
- The counts can also change due to dataset updates. Metrics are always calculated based on the latest dataset, so the data for a specific feed can vary from month to month as the latest dataset changes.

Does this answer your question? If not, could you clarify or provide more details?

**Comment by emmambd** [comment]
@cka-y Your second point does - I forgot we've added a fair number of feeds and so it makes sense we're seeing significantly more text-to-speech feeds. Thanks!

**Review by cka-y — APPROVED** [review]
LGTM 👍

**Pull request merged**
