### PR TITLE
adds basic cypress testing for Feeds page

### LINKED ISSUE #512: Final GTFS Schedule feed page: Bounding Box, Feed Summary, and Header(Cypress)
# Description

This issue adds the Cypres test to the GTFS Schedule feed page, #464.

# Basic Test Cases

- [x] Proper rendering of components
- [x] if the validation report exists: Error, Warnings, and Infos are rendered
- [ ] If the validation report doesn't exist, _TBD_? @emmambd 
- [ ] When errors are triggered during API calls: _TBD_?
- [x] Features component should be rendered 

** Please add more test cases as needed

### PR DESCRIPTION
**Pull request by indraneel**
closes #512 #513
does not mock API call

**Summary:**
image
**Expected behavior:** 

`yarn cypress:run` 

```
  Running:  feeds.cy.ts                                                                     (2 of 6)


  Feed page
    ✓ should render feed title and provider (2092ms)
    ✓ should render the last updated date (722ms)
    ✓ should render download button (645ms)
    ✓ should render data quality summary (741ms)
    ✓ should render feed summary (702ms)
    ✓ should render dataset history (680ms)
    ✓ should render feature chips (692ms)
    ✓ should have working links to validation reports (714ms)


  8 passing (7s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        8                                                                                │
  │ Passing:      8                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     7 seconds                                                                        │
  │ Spec Ran:     feeds.cy.ts                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  ```

**Testing tips:**

Provide tips, procedures and sample files on how to test the feature.
Testers are invited to follow the tips AND to try anything they deem relevant outside the bounds of the testing tips. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by indraneel** [comment]
This is my thought on how this should look. Crucially, this does not mock any API calls — open to feedback there

**Comment by indraneel** [comment]
Will need some help debugging this. The tests are failing because of missing `data-testid`s which I added in this same PR. 

```
  Running:  feeds.cy.ts                                                                     (2 of 6)


  Feed page
    1) should render feed title and provider
    2) should render the last updated date
    3) should render download button
    4) should render data quality summary
    5) should render feed summary
    6) should render dataset history
    7) should render feature chips
    8) should have working links to validation reports


  0 passing (36s)
  8 failing

  1) Feed page
       should render feed title and provider:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="feed-provider"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:8:0)

  2) Feed page
       should render the last updated date:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="last-updated"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:12:0)

  3) Feed page
       should render download button:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[id="download-latest-button"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:15:0)

  4) Feed page
       should render data quality summary:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="data-quality-summary"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:18:0)

  5) Feed page
       should render feed summary:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="location"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:25:0)

  6) Feed page
       should render dataset history:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="dataset-item"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:30:0)

  7) Feed page
       should render feature chips:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="feature-chips"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:33:0)

  8) Feed page
       should have working links to validation reports:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid="validation-report-html"]`, but never found it.
      at Context.eval (webpack://mobility-database/./cypress/e2e/feeds.cy.ts:37:0)

```

It looks like it's checking out the correct branch, so I'm not immediately sure what the issue is. Any thoughts @davidgamez? 

```
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/592/merge
  Note: switching to 'refs/remotes/pull/592/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 2e3f5f4 Merge 8aa271a7b9d670[61](https://github.com/MobilityData/mobility-feed-api/actions/runs/10016063613/job/27729821965?pr=592#step:2:68)5fcf229d710e3162f7e62b6a into 4b64f9f6df2d8dc838cd4f56da189e79dcebba6b
  ```

**Comment by davidgamez** [comment]
Hi @indraneel, I tested the branch locally, and I was also looking at the videos generated by Cypress on the GitHub actions. The key is the the _REACT_APP_FEED_API_BASE_URL_ parameter. Locally, we are pointing to _https://api-dev.mobilitydatabase.org_; in the GitHub actions, we are not setting the environment variable. This is why the API calls go to a relative path _/v1/feeds/mdb-516/_, as shown in the video. Currently, our UI is returning an empty page(HTTP 200) when a path that doesn't exist is requested. This is a different issue that we can address in the future. As for the current Cypress tests, creating and intercepting the HTTP request will fix the problem at the GH action( 🤞 ). I can give it a try on the API request intercept.
As an alternative solution, we can point Cypress tests to DEV; I would prefer to isolate the Cypress test for now to make sure the state/health of the DEV API environment adds no notice. This doesn't interfere with any plan in the future of creating a **real** 2E2 against a live API environment.

Regarding the question of how this can work on the production setup, the Cypress tests and unit tests always run against the dev setup, no matter the environment that the _main_ Github action will deploy to. 
Screenshot 2024-07-22 at 12 58 36 PM

https://github.com/user-attachments/assets/6710278d-b0fc-471b-9a87-a69708394a86

**Comment by davidgamez** [comment]
@indraneel I tried it, and I have a working version of the API mocks. Please merge it in your branch and change it as needed. Here is the PR against this branch, #593

**Comment by indraneel** [comment]
It worked @davidgamez! thanks!

**Review by davidgamez — APPROVED** [review]
LGTM

**Pull request merged**
