### PR TITLE
fix: mobile navigation matches desktop navigation

### LINKED ISSUE #205: Hamburger navigation should match desktop navigation items
Edit hamburger navigation to make it match with desktop navigation items

### PR DESCRIPTION
**Pull request by cka-y**
**Summary:**
Closes #205 

**Expected behavior:** 
The hamburger navigation matches the desktop navigation

When the user is not authenticated:
image

When the user is authenticated:
image

**Testing tips:**
- Reduce page width to <900px
- Click on hamburger navigation 
- Validate that the login button works properly
- Login to your account
- Click on the hamburger navigation once more
- Validate that the account options are available and match the desktop version (which you can see by increasing the page width to >=900px) 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Add or update any needed documentation to the repo
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by cka-y** [comment]
Needs #199 to be merged before merging

**Comment by emmambd** [comment]
@cka-y On the QA side, this looks good! 1 note: can we remove the Help and Account Details items on nav when authenticated? It goes to the same page as the Account link so it's redundant.

**Comment by cka-y** [comment]
@emmambd  I agree concerning the `Help` item. However, the`Account Details` is the only item that goes to the account page. Would you like maybe to rename it?

**Comment by emmambd** [comment]
@cka-y The Account header is clickable too, which is why I think Account Details is redundant/confusing. They both go to the same page.

**Review by davidgamez — APPROVED** [review]
LGTM

**Pull request merged**
