### PR TITLE
feat: Minor UI front end and email config changes

### LINKED ISSUE #180: Minor UI front end and email config changes
- Organization field should be removed if Organization is unknown
- Add Copied reaction to main field in Refresh Token, not just the tooltip 
- Grey out sign up button before until terms and conditions is checked
- Set default subject line for when users click the [api@mobilitydata.org](mailto:api@mobilitydata.org) link to "Remove Mobility Database account"

### PR DESCRIPTION
**Pull request by Neo2308**
**Summary:**

Fixes #180

**Expected behavior:** 

* Organization field should be removed if Organization is unknown
* Add Copied reaction to main field in Refresh Token, not just the tooltip
* Grey out sign up button before until terms and conditions is checked
* Set default subject line for when users click the api@mobilitydata.org link to "Remove Mobility Database account"

Screenshot 2024-01-06 at 2 37 41 AM

https://github.com/MobilityData/mobility-feed-api/assets/39310435/7f8c3a4d-e7b0-4af2-9b20-8c3d0416f52a

https://github.com/MobilityData/mobility-feed-api/assets/39310435/942ff380-69d7-4476-80a2-cd2f22b236e0

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Add or update any needed documentation to the repo
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by Neo2308** [comment]
@emmambd could you review this PR?

**Comment by emmambd** [comment]
Thanks for this great contribution, @Neo2308! I and our development team will take a look. How did you find our repo to contribute to?

**Comment by Neo2308** [comment]
I think I landed here from some issues in the catalog repo or the canonical gtfs validator repo. This felt like a super awesome idea. I know this repo is still not ready for production, but wanted to help with any minor issues I could take up.

**Comment by cka-y** [comment]
Hi @Neo2308! I'm ready to approve our first ever external contributors PR!
Could you please update your branch with the last changes from main?

**Comment by Neo2308** [comment]
Sorry about the delay. Ready for review
cc: @cka-y

**Review by cka-y — APPROVED** [review]
LGTM!

**Pull request merged**
