### PR TITLE
feat: Add our own DNS to GCP bucket links 

### PR DESCRIPTION
**Pull request by davidgamez**
**Summary:**

Added `files.mobilitydatabase.org` domain name to the batch storage bucket. Added the following names pere environment:
- PROD(not created yet) => files.mobilitydatabase.org
- QA(not created yet) => qa-files.mobilitydatabase.org
- DEV(not created yet) => dev-files.mobilitydatabase.org

**Expected behavior:** 

Files can be downloaded from files.mobilitydatabase.org example: https://files.mobilitydatabase.org/mdb-10/latest.zip (Not available currently)

**Testing tips:**
- This PR needs to be tested after merging as the reserved IP address will happen when terraform is applied.
- Download files a feed file from  the dev DNS, for example https://dev-files.mobilitydatabase.org/mdb-10/latest.zip
- Execute batch functions to verify that the DNS added to the DB matches with the newly created domain per environment.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by emmambd** [comment]
@davidgamez Looks good! Confirming here that this means we need to create an updated catalogs csv at some point post-launch with these new URLs, and I should let people know in our press release and README updates that the catalogs csv will be deprecated at a set time.

**Comment by cka-y** [comment]
Examples provided in the PR don't seem to be working

**Comment by davidgamez** [comment]
> Examples provided in the PR don't seem to be working

Sorry, I added the URL as HTTP instead of HTTPS, and the DNS for dev was still updating. Please try the DEV URL now. PROD is not available until we merge and deploy it.

**Comment by davidgamez** [comment]
> @davidgamez Looks good! Confirming here that this means we need to create an updated catalogs csv at some point post-launch with these new URLs, and I should let people know in our press release and README updates that the catalogs csv will be deprecated at a set time.

Yes, post-MVP, we can update the URLs to use this address for consistency.

**Review by cka-y — APPROVED** [review]
LGTM

**Pull request merged**
