### PR TITLE
feat: added sign in and sign up with apple UI

### LINKED ISSUE #178: Add Apple ID as SSO option to registration flow
Include Apple ID as an SSO registration option.

### PR DESCRIPTION
**Pull request by qcdyx**
**Summary:**
Closes #178 
Users of Mobility Database API should be able to sign in with Apple ID and password.
**Expected behavior:** 
image
image

**Testing tips:**
Signup/Login with your Apple ID and password.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by qcdyx** [comment]
As discussed with @davidgamez - Merge this PR only after Feature Flag PR is merged.

**Comment by davidgamez** [comment]
@qcdyx #332 is merged; you can rebase and add the Apple sign-in changes under a feature flag, Thanks!

**Comment by qcdyx** [comment]
If enableAppleSSO is false, don't show Sign in/up with Apple. @davidgamez 
image
image

**Review by emmambd — COMMENTED** [review]
Works for me! Waiting on approval from another developer.

**Review by davidgamez — APPROVED** [review]
LGTM!

**Pull request merged**
