### PR TITLE
ENH: add unit tests for GTFS and GTFS rt endpoints

### PR DESCRIPTION
**Pull request by goorui**
**Summary:**

Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Review by indraneel — APPROVED** [review]

**Comment by aronza** [comment]
@goorui  Can you rebase from main branch to run the unit tests here too?

**Comment by goorui** [comment]
@aronza looks like there's no conflict and I can just merge this one in?

**Comment by aronza** [comment]
> @aronza looks like there's no conflict and I can just merge this one in?

It's not about the conflicts but to make sure the unit tests are passing in CI. If you check the github CI in this MR it doesn't run the unit tests because it doesn't have my changes enabling the CI in this branch.

@indraneel  had to create a followup PR for the last one we've merged because we didn't do this.

**Comment by goorui** [comment]
@aronza thanks for the context. Just rebased, and looks like it's running the unittests now!

**Pull request merged**
